import type { Influencer, Task } from "@/types"

export const sampleInfluencers: Influencer[] = [
  {
    id: "1",
    handle: "@alexchen",
    name: "Alex Chen",
    platform: "Instagram",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
  },
  {
    id: "2",
    handle: "@sophiavlogs",
    name: "Sophia V",
    platform: "YouTube",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia",
  },
  {
    id: "3",
    handle: "@marcusbeats",
    name: "Marcus",
    platform: "TikTok",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus",
  },
  {
    id: "4",
    handle: "@emilystyle",
    name: "Emily Style",
    platform: "Instagram",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
  },
  {
    id: "5",
    handle: "@jaketech",
    name: "Jake Tech",
    platform: "YouTube",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jake",
  },
  {
    id: "6",
    handle: "@lenavibes",
    name: "Lena",
    platform: "TikTok",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lena",
  },
]

export const sampleTasks: Task[] = [
  {
    id: "task-1",
    title: "Create unboxing video for new product launch",
    influencer: sampleInfluencers[0],
    priority: "High",
    status: "Backlog",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 2500,
    deliverable: "Reel",
    assignees: [{ id: "a1", name: "Sarah", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah" }],
  },
  {
    id: "task-2",
    title: "Instagram carousel post about summer collection",
    influencer: sampleInfluencers[3],
    priority: "Medium",
    status: "Backlog",
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 1500,
    deliverable: "Post",
    assignees: [{ id: "a2", name: "Mike", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike" }],
  },
  {
    id: "task-3",
    title: "TikTok series - 5 trending sounds",
    influencer: sampleInfluencers[2],
    priority: "High",
    status: "In Progress",
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 3000,
    deliverable: "Short",
    assignees: [
      { id: "a1", name: "Sarah", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah" },
      { id: "a3", name: "Jordan", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan" },
    ],
  },
  {
    id: "task-4",
    title: "YouTube long-form review video",
    influencer: sampleInfluencers[1],
    priority: "Medium",
    status: "In Progress",
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 5000,
    deliverable: "Post",
    assignees: [{ id: "a2", name: "Mike", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike" }],
  },
  {
    id: "task-5",
    title: "Instagram Stories takeover - 24 hours",
    influencer: sampleInfluencers[4],
    priority: "Low",
    status: "In Progress",
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 1200,
    deliverable: "Story",
    assignees: [],
  },
  {
    id: "task-6",
    title: "Product styling guide photoshoot",
    influencer: sampleInfluencers[3],
    priority: "High",
    status: "Awaiting Approval",
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 4000,
    deliverable: "Post",
    assignees: [{ id: "a1", name: "Sarah", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah" }],
  },
  {
    id: "task-7",
    title: "TikTok duet challenge participation",
    influencer: sampleInfluencers[5],
    priority: "Medium",
    status: "Awaiting Approval",
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 800,
    deliverable: "Short",
    assignees: [{ id: "a3", name: "Jordan", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan" }],
  },
  {
    id: "task-8",
    title: "YouTube Shorts series - 10 videos",
    influencer: sampleInfluencers[1],
    priority: "Low",
    status: "Awaiting Approval",
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 2000,
    deliverable: "Short",
    assignees: [{ id: "a2", name: "Mike", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike" }],
  },
  {
    id: "task-9",
    title: "Instagram Reels - 3 trending audios",
    influencer: sampleInfluencers[0],
    priority: "High",
    status: "Done",
    dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 1800,
    deliverable: "Reel",
    assignees: [{ id: "a1", name: "Sarah", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah" }],
  },
  {
    id: "task-10",
    title: "TikTok brand collaboration announcement",
    influencer: sampleInfluencers[2],
    priority: "Medium",
    status: "Done",
    dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 2200,
    deliverable: "Short",
    assignees: [{ id: "a3", name: "Jordan", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan" }],
  },
  {
    id: "task-11",
    title: "YouTube community post series",
    influencer: sampleInfluencers[4],
    priority: "Low",
    status: "Done",
    dueDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 500,
    deliverable: "Post",
    assignees: [],
  },
  {
    id: "task-12",
    title: "Instagram Stories - Behind the scenes",
    influencer: sampleInfluencers[3],
    priority: "Medium",
    status: "Done",
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 1000,
    deliverable: "Story",
    assignees: [{ id: "a2", name: "Mike", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike" }],
  },
]
